# Generated by Django 2.2.28 on 2022-06-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipeingredient',
            table='api_recipe_ingredient',
        ),
    ]
