# Generated by Django 2.2.28 on 2022-06-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipeingredient',
            table='recipes_recipe_ingredient',
        ),
    ]
